########################################
# docker-compose up -d
#
# access via:
#   ssh root@<ip> -p 50001
#
# define alias in .ssh/config:
#   Host dmod-node1
#	    User root
#	    HostName node1
#	    Port 50001
#
#  Then use dmod-node1 in runbg.
#
# docker-compose up
# docker stack deploy -c docker-compose.yml dmod
#
# update image
# ansible nodes -m shell -a "docker image rm -f matthiaskoenig/dmod:latest"
# docker service update --force --image matthiaskoenig/dmod:latest dmod_dmod
#
# docker service create --name nginx-host --network host nginx
########################################

version: "3"
services:
  dmod:
    image: matthiaskoenig/dmod:latest
    ports:
      - target: 22
        published: 50001
        protocol: tcp
        mode: host
      
    volumes:
      - ~/.ssh/authorized_keys:/tmp/authorized_keys:ro
    deploy:
      replicas: 8

