# ----------------------------------------------------------
# Start dmod docker container
# ----------------------------------------------------------
# This docker-compose file starts the dmod container.
# It maps the internal docker ssh port 22 to 50001 thereby
# allowing access to the container via port 50001.
#
# In addition two volumes are mounted
# 1. a data volume to /root in the container (this should
#   be a NFS share when deploying on cluster).
#   For now just a local tmp folder is used here (~/tmp/dmod)
# 2. the local authorized keys for SSH access
#
# To start the container use
#      docker-compose up -d
# ----------------------------------------------------------

version: "3"
services:
  dmod:
    image: matthiaskoenig/dmod:latest
    ports:
      - "50001:22"
    volumes:
      - ~/tmp/dmod:/root
      - ~/.ssh/authorized_keys:/tmp/authorized_keys:ro

    network_mode: "host"
